#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeedQuestion {
    pub id: i64,
    pub seed_key: &'static str,
    pub text: &'static str,
    pub category: Option<&'static str>,
    pub source: Option<&'static str>,
}

pub const SEED_QUESTIONS: &[SeedQuestion] = &[
    SeedQuestion {
        id: 1,
        seed_key: "builtin_001",
        text: "What small part of today felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 2,
        seed_key: "builtin_002",
        text: "What small part of today helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 3,
        seed_key: "builtin_003",
        text: "What small part of today made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 4,
        seed_key: "builtin_004",
        text: "What small part of today invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 5,
        seed_key: "builtin_005",
        text: "What small part of today deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 6,
        seed_key: "builtin_006",
        text: "What small part of today would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 7,
        seed_key: "builtin_007",
        text: "What small part of today made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 8,
        seed_key: "builtin_008",
        text: "What small part of today brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 9,
        seed_key: "builtin_009",
        text: "What small part of today would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 10,
        seed_key: "builtin_010",
        text: "What small part of today made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 11,
        seed_key: "builtin_011",
        text: "What small part of today would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 12,
        seed_key: "builtin_012",
        text: "What small part of today felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 13,
        seed_key: "builtin_013",
        text: "What small part of today reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 14,
        seed_key: "builtin_014",
        text: "What small part of today turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 15,
        seed_key: "builtin_015",
        text: "Which quiet detail around you felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 16,
        seed_key: "builtin_016",
        text: "Which quiet detail around you helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 17,
        seed_key: "builtin_017",
        text: "Which quiet detail around you made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 18,
        seed_key: "builtin_018",
        text: "Which quiet detail around you invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 19,
        seed_key: "builtin_019",
        text: "Which quiet detail around you deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 20,
        seed_key: "builtin_020",
        text: "Which quiet detail around you would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 21,
        seed_key: "builtin_021",
        text: "Which quiet detail around you made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 22,
        seed_key: "builtin_022",
        text: "Which quiet detail around you brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 23,
        seed_key: "builtin_023",
        text: "Which quiet detail around you would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 24,
        seed_key: "builtin_024",
        text: "Which quiet detail around you made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 25,
        seed_key: "builtin_025",
        text: "Which quiet detail around you would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 26,
        seed_key: "builtin_026",
        text: "Which quiet detail around you felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 27,
        seed_key: "builtin_027",
        text: "Which quiet detail around you reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 28,
        seed_key: "builtin_028",
        text: "Which quiet detail around you turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 29,
        seed_key: "builtin_029",
        text: "What ordinary ritual felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 30,
        seed_key: "builtin_030",
        text: "What ordinary ritual helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 31,
        seed_key: "builtin_031",
        text: "What ordinary ritual made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 32,
        seed_key: "builtin_032",
        text: "What ordinary ritual invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 33,
        seed_key: "builtin_033",
        text: "What ordinary ritual deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 34,
        seed_key: "builtin_034",
        text: "What ordinary ritual would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 35,
        seed_key: "builtin_035",
        text: "What ordinary ritual made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 36,
        seed_key: "builtin_036",
        text: "What ordinary ritual brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 37,
        seed_key: "builtin_037",
        text: "What ordinary ritual would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 38,
        seed_key: "builtin_038",
        text: "What ordinary ritual made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 39,
        seed_key: "builtin_039",
        text: "What ordinary ritual would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 40,
        seed_key: "builtin_040",
        text: "What ordinary ritual felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 41,
        seed_key: "builtin_041",
        text: "What ordinary ritual reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 42,
        seed_key: "builtin_042",
        text: "What ordinary ritual turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 43,
        seed_key: "builtin_043",
        text: "Which gentle pause felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 44,
        seed_key: "builtin_044",
        text: "Which gentle pause helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 45,
        seed_key: "builtin_045",
        text: "Which gentle pause made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 46,
        seed_key: "builtin_046",
        text: "Which gentle pause invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 47,
        seed_key: "builtin_047",
        text: "Which gentle pause deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 48,
        seed_key: "builtin_048",
        text: "Which gentle pause would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 49,
        seed_key: "builtin_049",
        text: "Which gentle pause made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 50,
        seed_key: "builtin_050",
        text: "Which gentle pause brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 51,
        seed_key: "builtin_051",
        text: "Which gentle pause would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 52,
        seed_key: "builtin_052",
        text: "Which gentle pause made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 53,
        seed_key: "builtin_053",
        text: "Which gentle pause would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 54,
        seed_key: "builtin_054",
        text: "Which gentle pause felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 55,
        seed_key: "builtin_055",
        text: "Which gentle pause reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 56,
        seed_key: "builtin_056",
        text: "Which gentle pause turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 57,
        seed_key: "builtin_057",
        text: "What cozy corner in your day felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 58,
        seed_key: "builtin_058",
        text: "What cozy corner in your day helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 59,
        seed_key: "builtin_059",
        text: "What cozy corner in your day made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 60,
        seed_key: "builtin_060",
        text: "What cozy corner in your day invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 61,
        seed_key: "builtin_061",
        text: "What cozy corner in your day deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 62,
        seed_key: "builtin_062",
        text: "What cozy corner in your day would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 63,
        seed_key: "builtin_063",
        text: "What cozy corner in your day made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 64,
        seed_key: "builtin_064",
        text: "What cozy corner in your day brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 65,
        seed_key: "builtin_065",
        text: "What cozy corner in your day would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 66,
        seed_key: "builtin_066",
        text: "What cozy corner in your day made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 67,
        seed_key: "builtin_067",
        text: "What cozy corner in your day would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 68,
        seed_key: "builtin_068",
        text: "What cozy corner in your day felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 69,
        seed_key: "builtin_069",
        text: "What cozy corner in your day reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 70,
        seed_key: "builtin_070",
        text: "What cozy corner in your day turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 71,
        seed_key: "builtin_071",
        text: "Which conversation felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 72,
        seed_key: "builtin_072",
        text: "Which conversation helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 73,
        seed_key: "builtin_073",
        text: "Which conversation made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 74,
        seed_key: "builtin_074",
        text: "Which conversation invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 75,
        seed_key: "builtin_075",
        text: "Which conversation deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 76,
        seed_key: "builtin_076",
        text: "Which conversation would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 77,
        seed_key: "builtin_077",
        text: "Which conversation made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 78,
        seed_key: "builtin_078",
        text: "Which conversation brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 79,
        seed_key: "builtin_079",
        text: "Which conversation would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 80,
        seed_key: "builtin_080",
        text: "Which conversation made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 81,
        seed_key: "builtin_081",
        text: "Which conversation would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 82,
        seed_key: "builtin_082",
        text: "Which conversation felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 83,
        seed_key: "builtin_083",
        text: "Which conversation reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 84,
        seed_key: "builtin_084",
        text: "Which conversation turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 85,
        seed_key: "builtin_085",
        text: "What familiar sound felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 86,
        seed_key: "builtin_086",
        text: "What familiar sound helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 87,
        seed_key: "builtin_087",
        text: "What familiar sound made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 88,
        seed_key: "builtin_088",
        text: "What familiar sound invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 89,
        seed_key: "builtin_089",
        text: "What familiar sound deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 90,
        seed_key: "builtin_090",
        text: "What familiar sound would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 91,
        seed_key: "builtin_091",
        text: "What familiar sound made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 92,
        seed_key: "builtin_092",
        text: "What familiar sound brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 93,
        seed_key: "builtin_093",
        text: "What familiar sound would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 94,
        seed_key: "builtin_094",
        text: "What familiar sound made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 95,
        seed_key: "builtin_095",
        text: "What familiar sound would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 96,
        seed_key: "builtin_096",
        text: "What familiar sound felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 97,
        seed_key: "builtin_097",
        text: "What familiar sound reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 98,
        seed_key: "builtin_098",
        text: "What familiar sound turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 99,
        seed_key: "builtin_099",
        text: "Which comforting scent felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 100,
        seed_key: "builtin_100",
        text: "Which comforting scent helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 101,
        seed_key: "builtin_101",
        text: "Which comforting scent made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 102,
        seed_key: "builtin_102",
        text: "Which comforting scent invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 103,
        seed_key: "builtin_103",
        text: "Which comforting scent deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 104,
        seed_key: "builtin_104",
        text: "Which comforting scent would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 105,
        seed_key: "builtin_105",
        text: "Which comforting scent made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 106,
        seed_key: "builtin_106",
        text: "Which comforting scent brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 107,
        seed_key: "builtin_107",
        text: "Which comforting scent would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 108,
        seed_key: "builtin_108",
        text: "Which comforting scent made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 109,
        seed_key: "builtin_109",
        text: "Which comforting scent would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 110,
        seed_key: "builtin_110",
        text: "Which comforting scent felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 111,
        seed_key: "builtin_111",
        text: "Which comforting scent reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 112,
        seed_key: "builtin_112",
        text: "Which comforting scent turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 113,
        seed_key: "builtin_113",
        text: "What simple pleasure felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 114,
        seed_key: "builtin_114",
        text: "What simple pleasure helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 115,
        seed_key: "builtin_115",
        text: "What simple pleasure made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 116,
        seed_key: "builtin_116",
        text: "What simple pleasure invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 117,
        seed_key: "builtin_117",
        text: "What simple pleasure deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 118,
        seed_key: "builtin_118",
        text: "What simple pleasure would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 119,
        seed_key: "builtin_119",
        text: "What simple pleasure made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 120,
        seed_key: "builtin_120",
        text: "What simple pleasure brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 121,
        seed_key: "builtin_121",
        text: "What simple pleasure would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 122,
        seed_key: "builtin_122",
        text: "What simple pleasure made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 123,
        seed_key: "builtin_123",
        text: "What simple pleasure would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 124,
        seed_key: "builtin_124",
        text: "What simple pleasure felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 125,
        seed_key: "builtin_125",
        text: "What simple pleasure reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 126,
        seed_key: "builtin_126",
        text: "What simple pleasure turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 127,
        seed_key: "builtin_127",
        text: "Which soft memory felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 128,
        seed_key: "builtin_128",
        text: "Which soft memory helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 129,
        seed_key: "builtin_129",
        text: "Which soft memory made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 130,
        seed_key: "builtin_130",
        text: "Which soft memory invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 131,
        seed_key: "builtin_131",
        text: "Which soft memory deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 132,
        seed_key: "builtin_132",
        text: "Which soft memory would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 133,
        seed_key: "builtin_133",
        text: "Which soft memory made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 134,
        seed_key: "builtin_134",
        text: "Which soft memory brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 135,
        seed_key: "builtin_135",
        text: "Which soft memory would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 136,
        seed_key: "builtin_136",
        text: "Which soft memory made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 137,
        seed_key: "builtin_137",
        text: "Which soft memory would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 138,
        seed_key: "builtin_138",
        text: "Which soft memory felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 139,
        seed_key: "builtin_139",
        text: "Which soft memory reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 140,
        seed_key: "builtin_140",
        text: "Which soft memory turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 141,
        seed_key: "builtin_141",
        text: "What act of care felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 142,
        seed_key: "builtin_142",
        text: "What act of care helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 143,
        seed_key: "builtin_143",
        text: "What act of care made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 144,
        seed_key: "builtin_144",
        text: "What act of care invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 145,
        seed_key: "builtin_145",
        text: "What act of care deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 146,
        seed_key: "builtin_146",
        text: "What act of care would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 147,
        seed_key: "builtin_147",
        text: "What act of care made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 148,
        seed_key: "builtin_148",
        text: "What act of care brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 149,
        seed_key: "builtin_149",
        text: "What act of care would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 150,
        seed_key: "builtin_150",
        text: "What act of care made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 151,
        seed_key: "builtin_151",
        text: "What act of care would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 152,
        seed_key: "builtin_152",
        text: "What act of care felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 153,
        seed_key: "builtin_153",
        text: "What act of care reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 154,
        seed_key: "builtin_154",
        text: "What act of care turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 155,
        seed_key: "builtin_155",
        text: "Which shared moment felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 156,
        seed_key: "builtin_156",
        text: "Which shared moment helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 157,
        seed_key: "builtin_157",
        text: "Which shared moment made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 158,
        seed_key: "builtin_158",
        text: "Which shared moment invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 159,
        seed_key: "builtin_159",
        text: "Which shared moment deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 160,
        seed_key: "builtin_160",
        text: "Which shared moment would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 161,
        seed_key: "builtin_161",
        text: "Which shared moment made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 162,
        seed_key: "builtin_162",
        text: "Which shared moment brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 163,
        seed_key: "builtin_163",
        text: "Which shared moment would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 164,
        seed_key: "builtin_164",
        text: "Which shared moment made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 165,
        seed_key: "builtin_165",
        text: "Which shared moment would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 166,
        seed_key: "builtin_166",
        text: "Which shared moment felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 167,
        seed_key: "builtin_167",
        text: "Which shared moment reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 168,
        seed_key: "builtin_168",
        text: "Which shared moment turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 169,
        seed_key: "builtin_169",
        text: "What warm drink or meal felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 170,
        seed_key: "builtin_170",
        text: "What warm drink or meal helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 171,
        seed_key: "builtin_171",
        text: "What warm drink or meal made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 172,
        seed_key: "builtin_172",
        text: "What warm drink or meal invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 173,
        seed_key: "builtin_173",
        text: "What warm drink or meal deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 174,
        seed_key: "builtin_174",
        text: "What warm drink or meal would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 175,
        seed_key: "builtin_175",
        text: "What warm drink or meal made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 176,
        seed_key: "builtin_176",
        text: "What warm drink or meal brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 177,
        seed_key: "builtin_177",
        text: "What warm drink or meal would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 178,
        seed_key: "builtin_178",
        text: "What warm drink or meal made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 179,
        seed_key: "builtin_179",
        text: "What warm drink or meal would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 180,
        seed_key: "builtin_180",
        text: "What warm drink or meal felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 181,
        seed_key: "builtin_181",
        text: "What warm drink or meal reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 182,
        seed_key: "builtin_182",
        text: "What warm drink or meal turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 183,
        seed_key: "builtin_183",
        text: "Which bit of weather felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 184,
        seed_key: "builtin_184",
        text: "Which bit of weather helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 185,
        seed_key: "builtin_185",
        text: "Which bit of weather made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 186,
        seed_key: "builtin_186",
        text: "Which bit of weather invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 187,
        seed_key: "builtin_187",
        text: "Which bit of weather deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 188,
        seed_key: "builtin_188",
        text: "Which bit of weather would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 189,
        seed_key: "builtin_189",
        text: "Which bit of weather made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 190,
        seed_key: "builtin_190",
        text: "Which bit of weather brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 191,
        seed_key: "builtin_191",
        text: "Which bit of weather would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 192,
        seed_key: "builtin_192",
        text: "Which bit of weather made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 193,
        seed_key: "builtin_193",
        text: "Which bit of weather would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 194,
        seed_key: "builtin_194",
        text: "Which bit of weather felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 195,
        seed_key: "builtin_195",
        text: "Which bit of weather reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 196,
        seed_key: "builtin_196",
        text: "Which bit of weather turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 197,
        seed_key: "builtin_197",
        text: "What unhurried choice felt most like home?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 198,
        seed_key: "builtin_198",
        text: "What unhurried choice helped you breathe more slowly?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 199,
        seed_key: "builtin_199",
        text: "What unhurried choice made the room feel warmer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 200,
        seed_key: "builtin_200",
        text: "What unhurried choice invited you to linger a little longer?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 201,
        seed_key: "builtin_201",
        text: "What unhurried choice deserves more gratitude than it usually gets?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 202,
        seed_key: "builtin_202",
        text: "What unhurried choice would you gladly repeat tomorrow?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 203,
        seed_key: "builtin_203",
        text: "What unhurried choice made you feel quietly cared for?",
        category: Some("memory"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 204,
        seed_key: "builtin_204",
        text: "What unhurried choice brought a sense of calm without asking for attention?",
        category: Some("reflection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 205,
        seed_key: "builtin_205",
        text: "What unhurried choice would be lovely to savor again this week?",
        category: Some("home"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 206,
        seed_key: "builtin_206",
        text: "What unhurried choice made the evening softer?",
        category: Some("ritual"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 207,
        seed_key: "builtin_207",
        text: "What unhurried choice would you want to share with someone you love?",
        category: Some("comfort"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 208,
        seed_key: "builtin_208",
        text: "What unhurried choice felt especially grounding?",
        category: Some("gratitude"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 209,
        seed_key: "builtin_209",
        text: "What unhurried choice reminded you that enough can be plenty?",
        category: Some("connection"),
        source: Some("builtin"),
    },
    SeedQuestion {
        id: 210,
        seed_key: "builtin_210",
        text: "What unhurried choice turned an ordinary moment into something tender?",
        category: Some("memory"),
        source: Some("builtin"),
    },
];

#[cfg(test)]
mod tests {
    use super::SEED_QUESTIONS;
    use std::collections::HashSet;

    #[test]
    fn seed_dataset_contains_at_least_200_questions() {
        assert!(
            SEED_QUESTIONS.len() >= 200,
            "expected at least 200 questions, found {}",
            SEED_QUESTIONS.len()
        );
    }

    #[test]
    fn seed_dataset_uses_unique_seed_keys() {
        let unique_keys: HashSet<_> = SEED_QUESTIONS
            .iter()
            .map(|question| question.seed_key)
            .collect();

        assert_eq!(
            unique_keys.len(),
            SEED_QUESTIONS.len(),
            "seed keys must be unique"
        );
    }

    #[test]
    fn seed_dataset_uses_unique_texts() {
        let unique_texts: HashSet<_> = SEED_QUESTIONS
            .iter()
            .map(|question| question.text)
            .collect();

        assert_eq!(
            unique_texts.len(),
            SEED_QUESTIONS.len(),
            "question text must be unique"
        );
    }
}
